run:
  # increase timeout for cases when tests run in parallel with linters
  timeout: 20m
  # which dirs to skip: they won't be analyzed;
  skip-dirs:
    - vendor
    - pkg
  modules-download-mode: vendor

linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true
  gocyclo:
    # minimal code complexity to report
    min-complexity: 10
  maligned:
    # print struct with more effective memory layout
    suggest-new: true
  lll:
    line-length: 512

linters:
  enable-all: true
  disable:
    - goerr113
    - noctx
    - gofumpt
    - godot

issues:
  exclude-use-default: true
  exclude-rules:
    - path: _test\.go
      linters:
      - goconst
      - dupl
      - gomnd
      - gochecknoglobals
    - path: _suite_test\.go
      linters:
      - gochecknoglobals
    - path: cmd/simulator/main\.go
      linters:
      - gomnd
    - path: integration/util/k8s\.go
      linters:
      - gomnd
      - funlen
      - gosec
    - path: integration/eats/eats_suite_test.go
      linters:
      - gosec
  # Maximum issues count per one linter. Set to 0 to disable.
  max-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable
  max-same: 0

  # Show only new issues
  new: false
