[[constraint]]
  name = "github.com/deckarep/golang-set"
  version = "1.7.1"

[[constraint]]
  name = "code.cloudfoundry.org/go-loggregator"
  version = "7.1.0"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/tps"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"
