apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tasks.eirini.cloudfoundry.org
spec:
  group: eirini.cloudfoundry.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                guid:
                  type: string
                name:
                  type: string
                appGUID:
                  type: string
                appName:
                  type: string
                orgGUID:
                  type: string
                orgName:
                  type: string
                spaceGUID:
                  type: string
                spaceName:
                  type: string
                environment:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                lifecycle:
                  type: object
                  maxProperties: 1
                  properties:
                    docker:
                      type: object
                      properties:
                        image:
                          type: string
                        command:
                          type: array
                          items:
                            type: string
                        registryUsername:
                          type: string
                        registryPassword: #should this be secured somehow?
                          type: string
                    buildpack:
                      type: object
                      properties:
                        dropletHash:
                          type: string
                        dropletGUID:
                          type: string
                        startCommand:
                          type: string
            status:
              type: object
              properties:
                  state:
                    type: string
                    enum:
                    - Pending
                    - Running
                    - Completed
                    - Failed
                    default: Pending
                  message:
                    type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: tasks
    singular: task
    kind: Task
    shortNames:
      - task
